server:
  port: 8080
  dataDir: data
  shutdownTimeout: 30s

db:
  file: db/cc.db

session:
  bits: 256
  lru: 100
  expire: 720h # 30 days

puzzles:
  name: "Code && Chill"
  default: "test"
  events:
    - path: test
      config: ../cc-test/event.yaml
