server:
  port: 8080
  dataDir: data
  shutdownTimeout: 30s

db:
  file: db/cc.db

session:
  bits: 512
  expire: 720h # 30 days
  truncate: 24h
  cleanupSchedule: "0 5 * * *"

puzzles:
  name: "Code && Chill"
  default: "test"
  events:
    - path: test
      config: ../cc-test/event.yaml
