server:
  port: 8080
  dataDir: data
  shutdownTimeout: 30s

db:
  file: db/cc.db

session:
  bits: 256
  expire: 720h # 30 days
  truncate: 24h
  cleanupSchedule: "0 5 * * *"

auth:
  discord:
    clientID: "1423632113676062852"
    clientSecret: secret/discord.txt
    redirectURI: http://localhost:8080/auth/discord
    exchangeTimeout: 10s

puzzles:
  name: "Code && Chill"
  default: "test"
  events:
    - path: test
      config: ../cc-test/event.yaml
